feat: make hanging testcase optional
googleapis/doc-templates pull request #103
Opened 2021-01-12 21:08 UTC by dandhlee

In order to not have every PR go through a 20 minute testcase, and for any other tests that we may flag as optional, a `--test-all` flag has been added to be used as
```pytest --test-all tests```
which developers can locally test and as well as use this on continuous/nightly Kokoro builds.

2021-01-13 05:02 UTC, dandhlee commented
the builds sometime seems to take longer than the expected 30 minutes for an unknown reason, but to account for such difference, I've added the timer to increase to 4x fold (start with 30 minutes, then double it, then limit it to 2 hours). Ideally this should not take longer than 2 hours, and if it does mostly likely it's hanging rather than speed differences.

2021-01-13 16:07 UTC, tbpg requested changes

2021-01-13 16:07 UTC, tbpg commented on tests/conftest.py
> +    return request.config.getoption("--test-all")
Consider `--long`.

2021-01-13 16:32 UTC, dandhlee commented on tests/test_hanging.py
> +    times = {"timeout_count": 1, "timeout_initial": 1800, "timeout_limit": 4}
Variables no longer needed as retry method is no longer considered

2021-01-13 16:32 UTC, dandhlee commented on tests/test_hanging.py
> +            built = True
loop is no longer needed as retry method is no longer considered

2021-01-13 16:33 UTC, dandhlee commented on tests/test_hanging.py
> +                times["timeout_count"] += 1
timeout increased to 3 hours, will focus on making the test run faster rather than trying to zone in on the amount of time we need to give it.

2021-01-13 16:33 UTC, dandhlee commented on tests/conftest.py
> +    return request.config.getoption("--test-all")
done

2021-01-14 14:27 UTC, tbpg approved these changes
Thanks!

2021-01-14 14:28 UTC, merged